export const  CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const  ERRORHANDLER = 'ERRORHANDLER';
export const  LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const  ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const  EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const  FETCHING_BOOKS = 'FETCHING_BOOK';
export const  FETCHING_BOOKS_SUCCESS = 'FETCHING_BOOK_SUCCESS';
export const  FETCHING_BOOKS_ERROR = 'FETCHING_BOOK_ERROR';
export const  GET_SINGLE_BOOK = 'GET_SINGLE_BOOK';

